schema_version = "1.0.0"

[pipeline]
paddleocr_version = "3.7.0"
paddlepaddle_version = "3.3.1"
ocr_version = "PP-OCRv6"
detection_model_name = "PP-OCRv6_medium_det"
recognition_model_name = "PP-OCRv6_medium_rec"
model_source = "official_pretrained"
language = "en"
device = "cpu"
engine = "paddle_static"
use_doc_orientation_classify = false
use_doc_unwarping = false
use_textline_orientation = false
text_rec_score_threshold = 0.0
